### ISSUE TITLE
Bindings for properties

### ISSUE THREAD

**Issue by YorVeX** [kostya9/NetObsBindings#1]
In general I can't find any of the related definitions like obs_property, obs_properties or obs_properties_t in NetObsBindings right now.

Also, in order to work with that struct OBS provides several functions that I can't find anywhere either, e.g. obs_properties_create(), obs_properties_set_flags(), obs_properties_set_param(), obs_property_set_long_description and so on. See the [obs-properties.c](https://github.com/obsproject/obs-studio/blob/5582503d4f2030071784a60b9342961c25ccefe8/libobs/obs-properties.c) source file or the documentation for it [here](https://obsproject.com/docs/reference-properties.html).

Probably as a result of this e.g. obs_source_info.get_properties is currently declared with "void*" return type, where [actually it should be obs_properties_t](https://obsproject.com/docs/reference-sources.html#c.obs_source_info.get_properties) instead.

Would it be possible to add them and also correct the return types where it is used?

Thanks a lot!

**Comment by kostya9** [comment]
[Added](https://github.com/kostya9/NetObsBindings/commit/ccabdd3c978788b983d5eeb5cdb379a604cefbf8) properties bindings, and removed void* substitution for properties type. Check out the [0.0.1.16-alpha](https://www.nuget.org/packages/NetObsBindings/0.0.1.16-alpha) version

Properties functions will be in the ObsProperties class.

**Comment by YorVeX** [comment]
Wow, thanks, that was fast! Haven't tested the calls yet but at least the types are now there and it compiles so I would assume it's fine now.

Unfortunately I found another part that is missing and is also important in the context of properties (needed to be able to set default values), will open a new issue for that.
