### ISSUE TITLE
Add Image File Helper functions

### ISSUE THREAD

**Issue by YorVeX** [kostya9/NetObsBindings#11]
The [Image File Helper Functions](https://obsproject.com/docs/reference-libobs-graphics-image-file.html) are quite important when working with the already existing graphics API and I believe they are not in NetObsBindings yet, see [here](https://github.com/obsproject/obs-studio/blob/master/libobs/graphics/image-file.c) for the code.

**Comment by kostya9** [comment]
Aded [ObsImage](https://github.com/kostya9/NetObsBindings/blob/main/NetObsBindings/ObsInterop/ObsImageFile.cs) class to [0.0.1.28-alpha](https://www.nuget.org/packages/NetObsBindings/0.0.1.28-alpha)
