### ISSUE TITLE
Add functions from classes in /libobs/util - at least bmem

### ISSUE THREAD

**Issue by YorVeX** [kostya9/NetObsBindings#12]
I am currently investigating why my plugin is leaking memory in OBS according to the OBS log. I have one instance narrowed down to a call to Obs.obs_module_get_config_path(). This returns a string and I can see from other plug-in code that they call bfree() on that string after they finished using it, however, that function isn't available to me, since it's in [/libobs/util/bmem.c](https://github.com/obsproject/obs-studio/blob/8989cf5caffffaec3386f1770f07419c4cf7fca0/libobs/util/bmem.c#L138) and as far as I can see that isn't available in NetObsBindings right now.

On one hand those are not functions that directly belong to the OBS API, but on the other hand I don't see how else we could prevent such memory leaks without this, I cannot release this memory from C# code. So far I haven't found a case where I needed another function from classes in the /util folder, so I'd say if it's a one-liner somewhere we'd be on the safe side if you could just add them all, but if it's a lot of work then at least add bmem and I would create separate issues if I find more necessary base functions.

If you want to reproduce it yourself, change the set pointer export in your example plugin like this:
```cs
[UnmanagedCallersOnly(EntryPoint = "obs_module_set_pointer", CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
public static void SetPointer(nint obsModulePointer)
{
	Log("[blog] Pointer Saved!");
	ObsModulePointer = obsModulePointer;
	var configPath = Obs.obs_module_get_config_path((obs_module*)obsModulePointer, null); // memory leak here
}
```
Then run OBS with your plugin, exit OBS again and check the last line on the OBS log, it will now say "Number of memory leaks: 1".
If we could call bfree(configPath) afterwards it should be back to 0.

**Comment by YorVeX** [comment]
As a sidenode, I am currently working on an example plugin that includes
- usage of the OBS locale system to load various texts
- a property dialog accessible from the Tools menu with several example items
- a custom output that can be started/stopped with buttons from that Tools menu dialog and outputs frame timestamps to the OBS log each second
- a filter that can be added to async video sources like a Media Source and will then output the frame timestamps of that media source to the OBS log each second
- an image source that downloads the OBS logo from the OBS website using a .NET HttpClient and displays that on the source (see screenshots below)
- both the source and the filter again come with example properties and default values and implement a large number of events (activate, show, hide, deactivate, missing_files, video_render, update, save and so on, they will just log that these event functions are called)

I plan to release this on my GitHub and link to your NetObsBindings repo as a prerequisite and of course give you credit for laying the groundwork in general. The idea is that people can use this as a template when starting to write outputs, filters and sources and don't have to write all the event signatures manually, also it shows examples of how to implement these things. I want to contribute something after you've already done so much here, I hope that's fine with you.

![image](https://user-images.githubusercontent.com/528974/218236263-d0bda5bd-fe9e-4871-954d-41f4f094e832.png)

![image](https://user-images.githubusercontent.com/528974/218236410-d8aad97e-d61f-4461-bdbc-f75d535e9b18.png)

**Comment by kostya9** [comment]
Added [bmem](https://github.com/kostya9/NetObsBindings/blob/main/NetObsBindings/ObsInterop/ObsBmem.cs) bindings in [0.0.1.29-alpha](https://www.nuget.org/packages/NetObsBindings/0.0.1.29-alpha). It's unfortunate that some manual memory management is needed, but it's understandable. I am not really sure about the other ones in the util folder, will need to take a closer look later (e.g. some of them introduce threading, although .NET already has an idiomatic cross-platform way to do that).

Your example plugin looks awesome! Feel free to ping me anywhere (here or on twitter) when it will be published, I will add a link to it from this repository

**Comment by YorVeX** [comment]
Great, thanks, it's working, memory leaks are gone!

Yeah, it's a bit annoying, as a C# dev you're not used to that. But then again we have to work with pointers here all over the place anyway.

For most objects OBS is providing release functions as part of the API, e.g. ObsData.obs_data_release() or Obs.obs_source_release(), but not for functions that return strings and it can be very easily overlooked. For these I wrote a little helper function so that it can be easily retrieved as managed string and have the original memory allocation freed immediately again:
```cs
public static unsafe string GetString(sbyte* obsString)
{
  string managedString = Marshal.PtrToStringUTF8((IntPtr)obsString)!;
  ObsBmem.bfree(obsString);
  return managedString;
}
```

This is a global function from the Module class that I use everywhere, so from filter or source classes at least for functions that return strings it's now a one-liner:
```cs
string configPath = Module.GetString(Obs.obs_module_get_config_path(Module.ObsModule, null));
```
Will also be in my example plugin.

**Comment by YorVeX** [comment]
FYI, didn't upload the example plugin yet but one that actually has some use: https://github.com/YorVeX/xObsBrowserAutoRefresh
Corresponding obsproject.com posting is awaiting approval.

**Comment by YorVeX** [comment]
Example plugin is also uploaded, documentation is not complete yet though: https://github.com/YorVeX/ObsCSharpExample

**Comment by kostya9** [comment]
Added both to [README](https://github.com/kostya9/NetObsBindings)

**Comment by YorVeX** [comment]
Cool, hopefully we can inspire some more people to write C# plugins by giving them this headstart.
