### ISSUE TITLE
Add functions from bmem.h

### ISSUE THREAD

**Issue by YorVeX** [kostya9/NetObsBindings#13]
As an addition to #12 please also add functions from [bmem.h](https://github.com/obsproject/obs-studio/blob/master/libobs/util/bmem.h).

I am specifically missing bzalloc(), which unlike bmalloc() is defined in bmem.h and not bmem.c.

It can also be done from C# and this way even has the advantage that actually calling this with a type is an elegant way to create such an object:
![image](https://user-images.githubusercontent.com/528974/221333989-6f75e852-9d54-42a9-b649-8feb23be4d72.png)

Also I still think it's a bit weird to use memory management functions from OBS from C#. But then again it's what has the most chances to stay compatible through future updates of OBS, and since we already have the functions from bmem.c might as well go all the way to the end now. Reimplementing this base function in every plugin again now doesn't make sense either, as much as I like the elegance of my current solution 😛

**Comment by kostya9** [comment]
There is no reliable way to generate those, so added them manually. Skipped wchar_t ones, since I am not sure how to represent that in C#.

These should be available in 0.0.1.31-alpha in the ObsBmem class

**Comment by YorVeX** [comment]
You're using sizeof in your bzalloc implementation though, are you sure that is right? AFAIK sizeof returns the size needed in managed memory whereas Marshal.SizeOf\<T\> would return the size in unmanaged memory, which is what we want and what we also can rely on T to be, because of "where T : unmanaged".

**Comment by kostya9** [comment]
AFAIK for unmanaged types its the same - here, an [example in sharplab](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgAwFgBQiCM710wTgAoAiQHg3AQfeIEoBudaAZwEMAzAU3QG90ACPngApgAllGABlYQC82AHgCCAPkK1e/IaInS2AdSZgoogOYLlqtAF8caRqzY88ANgcAWQSLGSZsgCpmeAO4AFmxg9j4gPNAAtkxQTEZsACZcanx4RAzaAPYshD5UtDwA9MU8UNmB+oZQRmkOBIR4AHQAStDAwtFszQCSYqHZAA7ioQBuwgDGbAzNALL6DEFMADbNXmwA8iy+ZuZWaPRQzOwNznBuGp7aegbGuyqpaPwNmTl5BUWlVXe1PABGbEmTAgDHsFWAUSgsXiiRSz34GSamDaHS6PX6wEGI3GUxm80WyzWG22D0KdEs1hecAAzDwGMBIJNIfJODxNDwAMI0HgrbJ/AAiPIsQA=) (it even produces warnings if you dont add `T:unmanaged`)

**Comment by kostya9** [comment]
If you add a reference type - the unmanaged constraint will add a compilation error ([example](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgAwFgBQiCM710wTgAoAiQHg3AQfeIEoBudaAZwEMAzAU3QG90ACPngApgAllGABlYQC82AHgCCAPkK1e/IaInS2AdSZgoogOYLlqtAF8caRqzY88ANgcAWQSLGSZsgCpmeAO4AFmxg9j4gPNAAtkxQTEZsACZcanx4RAzaAPYshD5UtDwA9MU8UNmB+oZQRmkOBIR4AHQAStDAwtFszQCSYqHZAA7ioQBuwgDGbAzNALL6DEFMADbNXmwA8iy+ZuZWaPRQzOwNznBuGp7aegbGuyqpaPwNmTl5BUWlVXe1PABGbEmTAgDHsFWAUSgsXiiRSz34GSamDaHS6PX6wEGI3GUxm80WyzWG22D0KdEs1hecAAzDwGMBIJNIfJODxNDwAMI0HgrbJ/AAiPIA4jwAKI8g64OmIHjCzgWIA==))

**Comment by kostya9** [comment]
Found a more comprehensive answer, I was wrong - https://github.com/dotnet/runtime/issues/33802#issuecomment-934840795. Looks like this would be different for e.g. bool - [sharplab](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgAwFgBQiCM710wTgAoAiQHg3AQfeIEoBudaAZwEMAzAU3QG90ACPngApgAllGABlYQC82AHgBGAe0UAbAHyFa6AL440jVmx54AbMYAsgkWMkzZAFQ1UeAdwAWbMEfsge0ALZMUEwA5mwAJly8/HhEDNJsiiyE9lS0PAD0GTxQiq5MYFCiIdF8sYR4AHQAStDAwv5slQCSYp6KAA7ingBuwgDGbAyVALIFDG5MKpW2bADyLA5OWmjaQA==)

However, if you are planning to use T in managed code, then it would need to have the managed layout - e.g. you cant bzalloc a bool with size of `Marshal.Sizeof`(1byte), then change the value from C# as `*bool = true;`(4 bytes) - this would corrupt memory. So I am still not sure what would be the best API to use.

Now I am thinking maybe its best to remove this API (with generic T) in order not to confuse and make plugin authors make informed decisions on what they actually want.

**Comment by YorVeX** [comment]
> However, if you are planning to use T in managed code, then it would need to have the managed layout

I don't know how anyone would get the idea to try this, the whole reason for bzalloc()'s existence is to not only have a function for allocating unmanaged memory (for that the alloc functions from the Marshal class would suffice) but have one specifically tailored to be used with OBS (with the positive side effect that it also makes OBS track memory leaks for memory allocated with it). Also, it returns a void*, how would you use that with managed code?

**Comment by kostya9** [comment]
Fixed in 0.0.1.32-alpha. I added a comment to explicitly say that Marshal.SizeOf API is used for size, so that should be sufficient IMO.
