### ISSUE TITLE
Add media-io

### ISSUE THREAD

**Issue by YorVeX** [kostya9/NetObsBindings#16]
Some of the [media-io](https://github.com/obsproject/obs-studio/tree/master/libobs/media-io) scale and conversion functions would be extremely helpful when working with data a filter receives, because that data could have a variety of formats I otherwise would have to reimplement my own conversion routines for, whereas OBS already provides them.

If it's for some reason really hard to provide all of them through NetObsBindings at least [video-scaler-ffmpeg.c](https://github.com/obsproject/obs-studio/blob/master/libobs/media-io/video-scaler-ffmpeg.c) would be the most important for me personally, although I think audio-resampler-ffmpeg.c could also come in handy for others (or for a future me).

**Comment by kostya9** [comment]
In the latest version, there is the [ObsVideoScaler ](https://github.com/kostya9/NetObsBindings/blob/main/NetObsBindings/ObsInterop/ObsVideoScaler.cs)and [ObsAudioResampler](https://github.com/kostya9/NetObsBindings/blob/main/NetObsBindings/ObsInterop/ObsAudioResampler.cs), could you please check if they work for you

**Comment by YorVeX** [comment]
Unfortunately I still can't successfully compile NetObsBindings myself, so I can't really try without an updated NuGet package that contains this.

**Comment by YorVeX** [comment]
Any chance you could create a new NuGet package release soon? o:-)

**Comment by kostya9** [comment]
Haven't been able to test these functions yet. But as I see - they should be in the latest version already. They are in the source and visible for me when I reference the NuGet package, could you please double check?


![image](https://github.com/kostya9/NetObsBindings/assets/3115913/ab5695b6-ffe5-46f1-8372-f2842f5e13a5)

![image](https://github.com/kostya9/NetObsBindings/assets/3115913/a419094c-dc6b-47fc-ba2d-12cfa56033b9)

**Comment by YorVeX** [comment]
Oh, what the hell? When you said "in the latest version" I thought you referred to the main branch, I didn't get that you were already referring to a published NuGet release 😄 

Have been using 0.0.1.35 for a long time and never noticed it's there. Thanks a lot, will report back here as soon as I was able to test!

**Comment by YorVeX** [comment]
Not sure yet whether I will actually use them anytime soon, it turns out to be harder than I expected, cause I cannot easily get the information from OBS I need about a source to feed the scaling functions with the information they need. However, I can see that they are there with the correct signatures, I have no reason to believe they don't work, so let's just close this, should be fine. Thanks again!
