### ISSUE TITLE
VS Code support?

### ISSUE THREAD

**Issue by YorVeX** [kostya9/NetObsBindings#18]
The good news is that I am finally able to also generate the bindings myself. Not sure what changed, tried the same way like last time, but that was a long time ago and since then the ClangSharp generator has changed, so maybe that's what fixed it now.

I personally prefer VS Code, that's also what I am writing my plugins based on this library with. Therefore in my own fork I added tasks to build the library with release or debug config and even one to generate the bindings from within VS Code (and also that works like a charm):
![image](https://github.com/kostya9/NetObsBindings/assets/528974/868897d9-a2d4-4172-a325-27a15c8ec6c3)

I am happy to just keep this in my fork for myself, but I can also open a PR if you wish, I was just not sure whether you'd want that, because I saw that you currently explictily ignore the .vscode folder in the .gitignores file, which contradicts the idea of providing build and generate tasks and also default settings (VS code wants to know the default project file, so that also needs to go into settings.json).

The VS code related changes are here:
https://github.com/YorVeX/NetObsBindings/commit/00f0c636e828afbe3f3d58d84735ca8658d017f8

**Comment by YorVeX** [comment]
Another question, are you applying some manual changes after generation, or why do I get 2 additional files currently not in the repo and one modified file when I regenerate?
![image](https://github.com/kostya9/NetObsBindings/assets/528974/8fedd7cb-5815-41fb-95d7-88917b2e9060)

**Comment by kostya9** [comment]
Feel free to submit a PR for VS Code build tasks, I think that will do no harm for me and help others like yourself that use VS Code.

Regarding the second question - I do not make any manual changes after generating locally. Are the changes in ObsBase for `S__LINE__`, `INT_CUR_LINE` and `FILE_LINE`? I think those are #defines for stuff like current line and are useful to the C library but absolutely useless for the C# one. I think I should add them to excluded from generation, since they just produce noise (I think it resolves to the last occurence of such macro encountered by ClangSharpGenerator).

The other two `gs_...` and `pass_...` are unexpected to me. Could you please share what is changed there? And please share the current branch in the `obs-studio` folder (it should be release/29.1). And please share the version of clang and ClangSharpGenerator.

**Comment by YorVeX** [comment]
Yes, that's exactly it for ObsBase:
![image](https://github.com/kostya9/NetObsBindings/assets/528974/8b5dd95d-cf0e-4f38-a6cd-70a1082e3a11)
I also agree it would be the best to just exclude it.

Here's the two additional files I get:
[NetObsBindings-additional-files.zip](https://github.com/kostya9/NetObsBindings/files/12840931/NetObsBindings-additional-files.zip)

I used your PS scripts to update everything, it's indeed on release/29.1 version:
![image](https://github.com/kostya9/NetObsBindings/assets/528974/a4537d78-67e6-45bd-aa1a-6eb3a644c341)


I keep LLVM.LLVM updated through winget, it's currently on the latest 17.0.2 version.

![image](https://github.com/kostya9/NetObsBindings/assets/528974/5f65f7ff-e1a7-4c4c-ab5d-06a77dc9b69a)

**Comment by kostya9** [comment]
[Removed](https://github.com/kostya9/NetObsBindings/commit/bad2b1126ee068bbbc1374ca9a89f82d25608696) the noisy ObsBase macros from generation.

Also, I updated to the latest LLVM.LLVM (17.0.2) and ClangSharpPInvokeGenerator (16.0.0), but could not reproduce the additional changes, I do not see those two files appearing locally.

The differences should be somewhere in the configurations of our environments, but don't know where yet.

**Comment by YorVeX** [comment]
> [Removed](https://github.com/kostya9/NetObsBindings/commit/bad2b1126ee068bbbc1374ca9a89f82d25608696) the noisy ObsBase macros from generation.
> 
> Also, I updated to the latest LLVM.LLVM (17.0.2) and ClangSharpPInvokeGenerator (16.0.0), but could not reproduce the additional changes, I do not see those two files appearing locally.
> 
> The differences should be somewhere in the configurations of our environments, but don't know where yet.

Weird, I am not aware of any global config values for these tools that would explain this. I guess let's just leave it for now, maybe we will find out by accident at some point, I don't see anything important in there anyway.
