### ISSUE TITLE
Bindings for Data Settings

### ISSUE THREAD

**Issue by YorVeX** [kostya9/NetObsBindings#2]
Necessary in the context of properties (to set default values) and also in other areas is the [Data Settings API](https://obsproject.com/docs/reference-settings.html).

If I am not mistaken they are not yet part of the NetObsBindings right now. I would assume the relevant functions would be in an ObsData class, also I can't find obs_data_t and e.g. [obs_get_source_defaults](https://obsproject.com/docs/reference-sources.html#c.obs_get_source_defaults) has the settings parameter declared as void* instead in obs_source_info.get_defaults.

**Comment by kostya9** [comment]
Added ObsData bindings in [0.0.1.17-alpha](https://www.nuget.org/packages/NetObsBindings/0.0.1.17-alpha).

**Comment by YorVeX** [comment]
Looks good, obs_get_source_defaults now has the settings parameter declared as obs_data and I see lots of functions in ObsData, e.g. in a get_defaults handler I could now call ObsData.obs_data_set_default_string(), pass the settings parameter and set a default string setting. Again, thanks a lot!
