### ISSUE TITLE
obs_source_info.video_render has void* type for the effect parameter instead of gs_effect_t

### ISSUE THREAD

**Issue by YorVeX** [kostya9/NetObsBindings#3]
gs_effect itself seems to exist in NetObsBindings already and there is also lots of functions for the whole libobs/graphics area available in ObsGraphics, but still the [obs_source_info.video_render](https://obsproject.com/docs/reference-sources.html#c.obs_source_info.video_render) delegate uses void* type for the effect parameter so something still seems to be missing.

**Comment by kostya9** [comment]
Removed gs_effect type replacement in in [0.0.1.17-alpha](https://www.nuget.org/packages/NetObsBindings/0.0.1.17-alpha).

**Comment by YorVeX** [comment]
Parameter type is gs_effect now, thanks!
