### ISSUE TITLE
obs_source_info.create has void* type for the source parameter instead of obs_source_t

### ISSUE THREAD

**Issue by YorVeX** [kostya9/NetObsBindings#4]
obs_source and obs_weak_source itself seem to exist in NetObsBindings already and there is also lots of functions around sources available in ObsSource, but still the [obs_source_info.create](https://obsproject.com/docs/reference-sources.html#c.obs_source_info.create) delegate uses void* type for the source parameter so something still seems to be missing.

**Comment by kostya9** [comment]
Removed obs_source type replacement in in [0.0.1.17-alpha](https://www.nuget.org/packages/NetObsBindings/0.0.1.17-alpha).

**Comment by YorVeX** [comment]
Parameter type is obs_source now, thanks! I wonder a bit why I have written that lots of functions would be in ObsSource, either I confused something or they got lost with one of the other updates. If I am not mistaken ObsSource currently only has the obs_register_source_s() function and nothing else, and that's when the 2 most interesting areas for controlling OBS are sources and the frontend API. I will create two new issues for these 2 things.
