### ISSUE TITLE
Add OBS frontend API functions

### ISSUE THREAD

**Issue by YorVeX** [kostya9/NetObsBindings#7]
To really be able to do something meaningful with OBS I believe the two most important areas are source manipulation and the frontend API. This issue is regarding the latter.

Basically we need the functions defined [here](https://obsproject.com/docs/reference-frontend-api.html) so that basic things can be done like starting/stopping the stream, recording or replay buffer (or getting the current status of these functions, e.g. find out whether the recording is currently active). Other important things would be getting/setting the current transition/scene(collection)/profile or even creating/deleting them.

I guess having something like ObsFrontend for this would make sense to stay consistent with the current naming scheme.

**Comment by kostya9** [comment]
Published [0.0.1.18-alpha](https://www.nuget.org/packages/NetObsBindings/0.0.1.18-alpha) with ObsFrontendApi bindings
