### ISSUE TITLE
Add helper functions from obs-module.h (needed for localization)

### ISSUE THREAD

**Issue by YorVeX** [kostya9/NetObsBindings#8]
I can add the exports for obs_module_set_locale and obs_module_free_locale and they are called just fine, but in order to actually work with the OBS locale system plugins also need the obs_module_text() function from [obs-module.h](https://github.com/obsproject/obs-studio/blob/51050b3075a41d51251845ae3ffa00db0362e1e0/libobs/obs-module.h).

Also other functions from this file might be helpful though personally right now I am only interested in the mentioned locale function.

**Comment by kostya9** [comment]
C# doesn`t have such powerful macros, so I can't provide the macro in the library.

Added [text-lookup.h](https://github.com/obsproject/obs-studio/blob/dde4d57d726ed6d9e244ffbac093d8ef54e29f44/libobs/util/text-lookup.h) functions to ObsTextLookup class in [0.0.1.19-alpha](https://www.nuget.org/packages/NetObsBindings/0.0.1.19-alpha), and I think now you can declare `const char *obs_module_text(const char *val)`  (marked with UnmanagedCallers... attribute) with the same implementation as [here](https://github.com/obsproject/obs-studio/blob/51050b3075a41d51251845ae3ffa00db0362e1e0/libobs/obs-module.h#L112).

**Comment by kostya9** [comment]
I may consider using source generators for this stuff, but that's just an idea for now

**Comment by YorVeX** [comment]
Thanks! For anyone wondering how to use this when we can't use the templates, here is some code that is a first draft and not thoroughly error checked yet but in a first test my call to ObsText("TestText") returned "Test Successful" after having defined TestText="Test Successful" in \data\obs-plugins\MyPlugin\en-US.ini.

```cs
  const string DefaultLocale = "en-US";
  static unsafe obs_module* _obsModulePointer;
  static unsafe text_lookup* _textLookupModule = null;
  static string _locale = DefaultLocale;

  [UnmanagedCallersOnly(EntryPoint = "obs_module_set_pointer", CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
  public static unsafe void SetPointer(obs_module* obsModulePointer)
  {
    _obsModulePointer = obsModulePointer;
  }

  [UnmanagedCallersOnly(EntryPoint = "obs_module_set_locale", CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
  public static unsafe void ModuleSetLocale(char* locale)
  {
    var localeString = Marshal.PtrToStringUTF8((IntPtr)locale);
    if (!string.IsNullOrEmpty(localeString))
      _locale = localeString;
    if (_textLookupModule != null)
      ObsTextLookup.text_lookup_destroy(_textLookupModule);
    fixed (byte* defaultLocale = Encoding.UTF8.GetBytes(DefaultLocale), currentLocale = Encoding.UTF8.GetBytes(_locale))
      _textLookupModule = Obs.obs_module_load_locale(_obsModulePointer, (sbyte*)defaultLocale, (sbyte*)currentLocale);
  }

  [UnmanagedCallersOnly(EntryPoint = "obs_module_free_locale", CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
  public static unsafe void ModuleFreeLocale()
  {
    ObsTextLookup.text_lookup_destroy(_textLookupModule);
    _textLookupModule = null;
  }

  private static unsafe string ObsText(string identifier)
  {
    fixed (byte* lookupVal = Encoding.UTF8.GetBytes(identifier))
    {
      sbyte* lookupResult = null;
      ObsTextLookup.text_lookup_getstr(_textLookupModule, (sbyte*)lookupVal, &lookupResult);
      var resultString = Marshal.PtrToStringUTF8((IntPtr)lookupResult);
      if (string.IsNullOrEmpty(resultString))
        return "";
      else
        return resultString;
    }
  }
```

Should at least give everyone a start.
