### ISSUE TITLE
Add OBS Output API functions

### ISSUE THREAD

**Issue by YorVeX** [kostya9/NetObsBindings#9]
It would be great to have the necessary API methods available to register output functions, see [here](https://obsproject.com/docs/reference-outputs.html) or [here](https://github.com/obsproject/obs-studio/blob/61284cf9bafc3d2c9e2c533c436f8fd38c6d187e/libobs/obs-output.c) for details.

**Comment by kostya9** [comment]
Added the function to register output to [ObsOutput ](https://github.com/kostya9/NetObsBindings/blob/main/NetObsBindings/ObsInterop/ObsOutput.cs)class in [0.0.1.23-alpha](https://www.nuget.org/packages/NetObsBindings/0.0.1.23-alpha)
